### ISSUE TITLE
Change datavalues dimensions

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-recoding#5]
Change datavalues dimensions: Org. units, period, dataset attribute (if any)
- [ ] Remove each datavalue
- [ ] Assign each datavalue to the correct dimensions (bulk import)

**Comment by adrianq** [comment]
@ivanarrizabalaga  This an excerpt from a @josemp10 mail that provides all the information that we need to accomplish this task:
estuve chequeando la documentación y parece que tienes todo lo que necesitas aquí: http://dhis2.github.io/dhis2-docs/2.24/en/developer/html/ch01s17.html

Te comento.

1) Borrar Davalues -> La llamada (obviamente con DELETE):

../api/24/dataValues?de=s46m5MS0hxu&pe=201301&ou=DiszpKrYNg8&co=Prlt0C1RF0s

Donde de es el UID del dataelement, pe, el periodo, el ou el uid de la org. unit, y co el el uid de la category option combinacion (mujer, 15-19 años). Estoy casi seguro que si no se especifica el co, borra los datavalues de ese dataelement para todas las categorías. Así que me imagino que es mejor no especificar el co.

Yo no he visto en la documentación algo que sea como borrar bulk Datavalues (aunque no digo que no se pueda hacer). Existe un importStrategy = DELETE pero es para archivos CSV....y yo nunca lo he utilizado

1) Insertar datavalues -> Puede ser un bulk insertion por dataset

Llamada  a  la API con POST (aunque me imagino que PUT vaya a funcionar igual)

../api/24/dataValueSets

Payload

{
  "dataSet": "dataSetID",
  "completeDate": "date",
  "period": "period",
  "orgUnit": "orgUnitID",
  "attributeOptionCombo", "aocID",
  "dataValues": [
    { "dataElement": "dataElementID", "categoryOptionCombo": "cocID", "value": "1", "comment": "comment1" },
    { "dataElement": "dataElementID", "categoryOptionCombo": "cocID", "value": "2", "comment": "comment2" },
    { "dataElement": "dataElementID", "categoryOptionCombo": "cocID", "value": "3", "comment": "comment3" }
  ]
}

categoryOptionCombo es opcional, solamente para dataelements que tengan opciones...

attributeoptioncombo es opcional, solo para datasets que tengan datasetattributes, y en ese caso es el UID de la combinación de opciones seleccionada...

**Comment by ivanarrizabalaga** [comment]
The **co** param is required since its the one that sets a combination of attributes selection that points exactly to the value itself.

Example:

The value: 

``` json
{
        "id":"s46m5MS0hxu-psbwp3CQEhs",
            "val":"1979",
    "com":"false"
  }
```

Can be retrieved using:

http://127.0.0.1:8080/api/24/dataValues.json?de=s46m5MS0hxu&pe=201608&ou=Rp268JB6Ne4&co=psbwp3CQEhs

Where **psbwp3CQEhs** points to the combination of attributes/values for that given entry.

**Comment by ivanarrizabalaga** [comment]
@josemp10  I've talking to @adrianq and we are not sure about a couple of attributes regarding the POST of datavalues:

As I said in the previous comment in order to get the datavalue (even when there are no attributes/categories) you have to put a **co** param that points to a combination of pairs (attributes/values).

Thus I guess that in order to post that value into a new combination I need to fulfill these attributes:
- attributeOptionCombo: For the dataset itself
- categoryOptionCombo: For each datavalue

(see here: http://dhis2.github.io/dhis2-docs/2.24/en/developer/html/ch01s17.html).

Do you know where to get those values??

**Comment by ivanarrizabalaga** [comment]
I've taken a look into this call:

http://127.0.0.1:8080/dhis-web-dataentry/getMetaData.action

and now I know that there is these relationships:

 1 categoryCombo --< N Categories  --< N Options

where:
- **categoryCombo**, is a row that joins a set of attributes for each dataset. (Ex: Implementing Partner and Projects)
- **category**, is every attribute that might be fulfill in a given dataset (Ex: Implementing Partner)
- **option**, every possible answer for that category (Ex: AIDSRelief Consortium)

**Comment by josemp10** [comment]
https://play.dhis2.org/demo/api/categoryCombos/O4VaNks6tta.json?fields=categoryOptionCombos[id,displayName]

**Comment by ivanarrizabalaga** [comment]
@adrianq the basic scenario is already working though I still need to check some details:
- Distinguish when the attributes/data combination has not changed
- Confirm that default Combo Option (when NO attributes at all) is working ok
